### ISSUE TITLE
Incorrect card evaluator

### ISSUE THREAD

**Issue by Jacobrc2018** [simster7/PocketRockets#54]
When testing the hand: "AC JS AS QH QC 7C 8D"
The following output:
`{31, 45, 38, 9, 12, 23, 36}, HandStrength:engine.HandStrength{5, 10}, PlayerIndex:0, HandName:"Straight"}}`
when the cards are not a straight but rather a two pair.

**Comment by simster7** [comment]
Thanks for the bug report! Fixed in https://github.com/simster7/PocketRockets/pull/55

**Comment by Jacobrc2018** [comment]
Fixed the one issue of detecting as a straight, but in the case that there is a pair, two pair, or three of a kind it wont detect a straight. "KS JH AH QH QC TH QS" returns `{11, 22, 25, 23, 36, 21, 10}, HandStrength:engine.HandStrength{4, 10, 12, 11}, PlayerIndex:0, HandName:"Three Of A Kind"}}`

**Comment by simster7** [comment]
@Jacobrc2018 nice catch! Seems like the port from Python wasn't as smooth as I thought. Take a look at https://github.com/simster7/PocketRockets/pull/56 and let me know if you find any more issues
